### ISSUE TITLE
PlayerDeathEvent to MoneyThief v1.2.10

### ISSUE THREAD

**Issue by madtomic** [Ratismal/MoneyThief#5] opened 2015-07-28 13:44 UTC
http://pastebin.com/Rcebq7uA

I didn't fix it. I can't make of this. This is weird.

**Comment by madtomic** [comment] 2015-07-28 13:44
It happens randomly with different players.

**Comment by Ratismal** [comment] 2015-07-28 15:26
Ok, I'm looking into this issue right now.

Out of curiosity, what fix did you apply that initially made it appear to work?

**Comment by Ratismal** [comment] 2015-07-28 15:34
Does this happen every time a player kills a baby zombie, or sporadically? Because on my test server I killed one and nothing bad happened.

**Comment by Ratismal** [comment] 2015-07-28 16:26
I think I know what is causing this issue. The event listeners are trying to add money to a non-existent account. This could be an issue with iConomy, which would explain why I was unable to recreate the issue.
Can you ensure that iConomy is working correctly and report back to me with the results? If that's not the cause of the issue, I'll make you a debug version of MoneyThief to get some more information.

**Comment by madtomic** [comment] 2015-07-28 17:12
Ok, I'm thinking it's my custom build iconomy. Let me check and double check and get back with you. If need. I will send you a copy of it so you can see what is causing the issue.

**Comment by madtomic** [comment] 2015-07-28 17:30
I PM you on bukkit of my custom bulid iconomy. Maybe you can check it out. The only change was not use username but use uuid instead.

**Comment by madtomic** [comment] 2015-07-28 17:34
Like you said, I'm thinking it's how it is trying to add money to a non-existent account because iconomy changed to uuid and not username?

**Comment by Ratismal** [comment] 2015-07-28 17:43
Do any of your other economy plugins work?
My suggestion would be to delete all of the economy files so that it can generate new ones. Make sure to make backups first!
If this doesn't work, it might be an issue with Vault. Due to how iConomy uses player names, it might be an issue that it doesn't support your custom version with UUID's. As seen [here](https://github.com/MilkBowl/Vault/blob/master/src/net/milkbowl/vault/economy/plugins/Economy_iConomy6.java), the withdrawPlayer and depositPlayer functions use playernames instead of UUID's. If this is the case, I have no idea what to do.

**Comment by madtomic** [comment] 2015-07-28 17:45
Then, I would need a custom build of vault to support uuid. ERR

**Comment by madtomic** [comment] 2015-07-28 17:45
Thank you for looking into this. I'll try a fix of vault and see. =)

**Comment by Ratismal** [comment] 2015-07-29 02:04
No problem. I'm going to close this issue now, but if anything else arises related to it feel free to keep commenting them here.

**Closed as completed by Ratismal** 2015-07-29 02:04 UTC
Labels: bug
